# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainW.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 876)
        MainWindow.setMaximumSize(QtCore.QSize(1024, 1024))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("200px-Friedrich_Wilhelm_Bessel.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 21, 25))
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"Times New Roman\";")
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 21, 25))
        self.label_2.setStyleSheet("font: 16pt \"Times New Roman\"")
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 21, 25))
        self.label_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"Times New Roman\";")
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 220, 20, 25))
        self.label_4.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 21, 25))
        self.label_5.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(120, 80, 881, 631))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 330, 31, 25))
        self.label_6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"Times New Roman\";")
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setScaledContents(False)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 370, 31, 25))
        self.label_7.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"Times New Roman\";")
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setScaledContents(False)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 410, 31, 25))
        self.label_8.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"Times New Roman\";")
        self.label_8.setTextFormat(QtCore.Qt.RichText)
        self.label_8.setScaledContents(False)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 450, 31, 25))
        self.label_9.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"Times New Roman\";")
        self.label_9.setTextFormat(QtCore.Qt.RichText)
        self.label_9.setScaledContents(False)
        self.label_9.setObjectName("label_9")
        self.alpha = QtWidgets.QLineEdit(self.centralwidget)
        self.alpha.setGeometry(QtCore.QRect(40, 50, 40, 25))
        self.alpha.setObjectName("alpha")
        self.betta = QtWidgets.QLineEdit(self.centralwidget)
        self.betta.setGeometry(QtCore.QRect(40, 80, 40, 25))
        self.betta.setObjectName("betta")
        self.k = QtWidgets.QLineEdit(self.centralwidget)
        self.k.setEnabled(True)
        self.k.setGeometry(QtCore.QRect(40, 110, 40, 25))
        self.k.setObjectName("k")
        self.delta = QtWidgets.QLineEdit(self.centralwidget)
        self.delta.setGeometry(QtCore.QRect(40, 220, 40, 25))
        self.delta.setObjectName("delta")
        self.epsilon = QtWidgets.QLineEdit(self.centralwidget)
        self.epsilon.setGeometry(QtCore.QRect(40, 190, 40, 25))
        self.epsilon.setObjectName("epsilon")
        self.axesA = QtWidgets.QLineEdit(self.centralwidget)
        self.axesA.setGeometry(QtCore.QRect(40, 330, 40, 25))
        self.axesA.setObjectName("axesA")
        self.axesB = QtWidgets.QLineEdit(self.centralwidget)
        self.axesB.setGeometry(QtCore.QRect(40, 370, 40, 25))
        self.axesB.setObjectName("axesB")
        self.axesC = QtWidgets.QLineEdit(self.centralwidget)
        self.axesC.setGeometry(QtCore.QRect(40, 410, 40, 25))
        self.axesC.setObjectName("axesC")
        self.axesD = QtWidgets.QLineEdit(self.centralwidget)
        self.axesD.setGeometry(QtCore.QRect(40, 450, 40, 25))
        self.axesD.setObjectName("axesD")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 760, 131, 51))
        self.pushButton.setStyleSheet("background-color: rgb(255, 183, 120);")
        self.pushButton.setObjectName("pushButton")
        self.labelFunction = QtWidgets.QLabel(self.centralwidget)
        self.labelFunction.setGeometry(QtCore.QRect(260, 0, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(10)
        self.labelFunction.setFont(font)
        self.labelFunction.setAutoFillBackground(True)
        self.labelFunction.setStyleSheet("")
        self.labelFunction.setObjectName("labelFunction")
        self.tau = QtWidgets.QLineEdit(self.centralwidget)
        self.tau.setGeometry(QtCore.QRect(40, 500, 40, 25))
        self.tau.setText("")
        self.tau.setObjectName("tau")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 500, 21, 25))
        self.label_11.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"Times New Roman\";")
        self.label_11.setTextFormat(QtCore.Qt.RichText)
        self.label_11.setScaledContents(False)
        self.label_11.setObjectName("label_11")
        self.coef_n = QtWidgets.QLineEdit(self.centralwidget)
        self.coef_n.setEnabled(True)
        self.coef_n.setGeometry(QtCore.QRect(40, 540, 40, 25))
        self.coef_n.setObjectName("coef_n")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 540, 41, 25))
        self.label_12.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"Times New Roman\";")
        self.label_12.setTextFormat(QtCore.Qt.RichText)
        self.label_12.setScaledContents(False)
        self.label_12.setObjectName("label_12")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(840, 710, 161, 111))
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.fi = QtWidgets.QLineEdit(self.centralwidget)
        self.fi.setGeometry(QtCore.QRect(40, 140, 40, 25))
        self.fi.setObjectName("fi")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(19, 140, 21, 25))
        self.label_13.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.label_13.setTextFormat(QtCore.Qt.RichText)
        self.label_13.setScaledContents(False)
        self.label_13.setObjectName("label_13")
        self.psi = QtWidgets.QLineEdit(self.centralwidget)
        self.psi.setGeometry(QtCore.QRect(40, 280, 40, 25))
        self.psi.setObjectName("psi")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 280, 20, 25))
        self.label_14.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.label_14.setTextFormat(QtCore.Qt.RichText)
        self.label_14.setScaledContents(False)
        self.label_14.setObjectName("label_14")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(20, 250, 20, 31))
        self.label_17.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.label_17.setTextFormat(QtCore.Qt.RichText)
        self.label_17.setScaledContents(False)
        self.label_17.setObjectName("label_17")
        self.ro = QtWidgets.QLineEdit(self.centralwidget)
        self.ro.setGeometry(QtCore.QRect(40, 250, 40, 25))
        self.ro.setObjectName("ro")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "α:"))
        self.label_2.setText(_translate("MainWindow", "β:"))
        self.label_3.setText(_translate("MainWindow", "k:"))
        self.label_4.setText(_translate("MainWindow", "δ:"))
        self.label_5.setText(_translate("MainWindow", "ε:"))
        self.label_6.setText(_translate("MainWindow", "A:"))
        self.label_7.setText(_translate("MainWindow", "B:"))
        self.label_8.setText(_translate("MainWindow", "C:"))
        self.label_9.setText(_translate("MainWindow", "D:"))
        self.pushButton.setText(_translate("MainWindow", "Очистить"))
        self.labelFunction.setText(_translate("MainWindow", "x = α*x+β*y*y+k*x*x+φ\n"
"y = δ*x*x+ε*y+ρ*x+ψ"))
        self.label_11.setText(_translate("MainWindow", "    τ:"))
        self.label_12.setText(_translate("MainWindow", "N:"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#ff5500;\">Золотова Элина</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#ff5500;\">ИТ-31БО</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "φ:"))
        self.label_14.setText(_translate("MainWindow", "ψ:"))
        self.label_17.setText(_translate("MainWindow", "ρ:"))
        self.action.setText(_translate("MainWindow", "Ничеси"))
        self.action_2.setText(_translate("MainWindow", "Фига как можно!"))
        self.action_3.setText(_translate("MainWindow", "Кааааеф"))

